"""Flat-limit fans (boundary star planar) -- first survey."""
from patchlib import *
from fractions import Fraction as Fr
import numpy as np
# hexagonal lattice in plane x+y+z=0, normal n=(1,1,1)
u=(1,-1,0); w=(0,1,-1); n=(1,1,1)
def L(a,b,h=0): return tuple(a*u[c]+b*w[c]+h*n[c] for c in range(3))
frame=[(1,-1,0),(1,1,-2)]
hexring=[L(1,0),L(1,1),L(0,1),L(-1,0),L(-1,-1),L(0,-1)]   # 6 neighbours of 0 in the lattice generated by u,w (u.w=-1 so angle 120)
def fan(ring,q,z=(0,0,0)):
    m=len(ring); return [[q,z,ring[j],ring[(j+1)%m]] for j in range(m)],[(j,(1,2,3)) for j in range(m)]
for h in (Fr(1,2),1,2):
    mac,gf=fan(hexring,L(0,0,h))
    P=Patch(mac,gf,3); print('hex equilateral fan, apex on axis h=',h, moment_rank_mod(P,frame), kappa_float(P,frame))
for q in [L(Fr(1,5),Fr(1,7),1), L(Fr(1,3),0,1)]:
    mac,gf=fan(hexring,q)
    P=Patch(mac,gf,3); print('hex equilateral fan, apex off axis',q, moment_rank_mod(P,frame), kappa_float(P,frame))
# square ring in xy-plane (right isosceles faces), apex on axis
sq=[(1,0,0),(0,1,0),(-1,0,0),(0,-1,0)]
P=Patch(*fan(sq,(0,0,1)),3); print('square fan apex on axis', moment_rank_mod(P,[(1,0,0),(0,1,0)]), kappa_float(P,[(1,0,0),(0,1,0)]))
# pure fan-only fields (subtract single-macro contribution): single macro fields in the square fan
